name: SSISAuth
version: '1.0'
main: com.keii.ssisauth.SSISAuth
api-version: 1.19

commands:
  who:
    description: Get real minecraft username of nick
    usage: /who <user eg. WillemD>
    permission: ssisauth.who
  teleportplayer:
    description: teleport
    aliases: tpp
    usage: /teleportplayer <player> [player]
    permission: ssisauth.teleportplayer
  reloadusers:
    description: reloadusers
    usage: /reloadusers
    permission: ssisauth.reloadusers